[package]
name = "openmetrics-client"
version = "0.1.0"
authors = ["Qinxuan Chen <https://github.com/koushiro>"]
edition = "2021"
rust-version = "1.75.0"
readme = "README.md"
description = "Another Open Metrics client library in Rust."
license = "Apache-2.0"
keywords = ["openmetrics",  "metrics", "prometheus"]
repository = "https://github.com/koushiro/openmetrics-client"
homepage = "https://github.com/koushiro/openmetrics-client"
documentation = "https://docs.rs/openmetrics-client"

#[features]
#default = ["protobuf"]
#protobuf = ["dep:prost", "dep:prost-build", "dep:prost-types"]

#[build-dependencies]
#prost-build = { version = "0.13.5", optional = true }

[dependencies]
dtoa = "1.0"
itoa = "1.0"
parking_lot = "0.12"
paste = "1.0"
#prost = { version = "0.13.5", optional = true }
#prost-types = { version = "0.13.5", optional = true }
