[workspace]
resolver = "2"
members = [
    "client",
    "client/derive",
    "examples",
]

[workspace.package]
edition = "2021"
rust-version = "1.75.0"
license = "Apache-2.0"
homepage = "https://github.com/koushiro/openmetrics-client"
repository = "https://github.com/koushiro/openmetrics-client"
