[package]
name = "openmetrics-client"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
dtoa = "1.0"
itoa = "1.0"
parking_lot = "0.12"
paste = "1.0"
