# Basic
edition = "2021"
max_width = 100
use_small_heuristics = "Max"
# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
# Consistency
newline_style = "Unix"
# Misc
chain_width = 80
match_block_trailing_comma = true
use_field_init_shorthand = true
merge_derives = false
# Format comments
comment_width = 100
wrap_comments = true
